[package]
name = "is-odd-rs"
version = "0.2.0"
edition = "2021"
license = "AGPL-3.0"
description = "a stupid program to check if the number is odd or even. written in rust. may NOT be used as a library"

[dependencies]


[[bin]]
name = "is-odd"
path = "src/main.rs"